name: BuildBattlePro
version: 4.9.3
main: me.drawe.buildbattle.BuildBattle
load: POSTWORLD
api-version: 1.13
website: https://www.spigotmc.org/resources/buildbattlepro-1-8-1-12-2.49587/
softdepend: [PlaceholderAPI, MVdWPlaceholderAPI, Vault, Multiverse-Core, PointsAPI, Vault, HolographicDisplays, Citizens, LeaderHeads]
author: TheRealDrawe
description: BuildBattlePro plugin
commands:
 buildbattle:
  aliases: [bb]
 settheme:
permissions:
  buildbattlepro.*:
    description: Gives access to all BuildBattle commands
    children:
     buildbattlepro.admin: true
  buildbattlepro.start:
    description: Allows you to start BuildBattle game
    default: op
  buildbattlepro.stop:
    description: Allows you to stop BuildBattle game
    default: op
  buildbattlepro.create:
    description: Allows you to create BuildBattle arena and staff around it
    default: op
  buildbattlepro.particle.*:
    description: Allow to place all particles
    default: op
    children:
      buildbattlepro.particle.heart: true
      buildbattlepro.particle.happy: true
      buildbattlepro.particle.angry: true
      buildbattlepro.particle.lava: true
      buildbattlepro.particle.water: true
      buildbattlepro.particle.note: true
      buildbattlepro.particle.glyph: true
      buildbattlepro.particle.slime: true
      buildbattlepro.particle.mobspawner: true
      buildbattlepro.particle.explosion: true
      buildbattlepro.particle.crit: true
      buildbattlepro.particle.witch: true
      buildbattlepro.particle.splash: true
      buildbattlepro.particle.cloud: true
      buildbattlepro.particle.portal: true
      buildbattlepro.particle.firework: true
      buildbattlepro.particle.redstone: true
      buildbattlepro.particle.snowball: true
  buildbattlepro.admin:
    description: Allows you to reload plugin
    default: op
    children:
      buildbattlepro.start: true
      buildbattlepro.stop: true
      buildbattlepro.create: true
      buildbattlepro.bypass: true
      buildbattlepro.party: true
      buildbattlepro.joinfull: true
      buildbattlepro.manage.reports: true
  buildbattlepro.joinfull:
    description: Join full arena
    default: op
  buildbattlepro.join:
    description: Join arena permission
    default: true
  buildbattlepro.party:
    description: Create party permission
    default: op
  buildbattlepro.party.size.*:
    description: Unlimited players in party
    default: op
  buildbattlepro.leave:
    description: Leave arena permission
    default: true
  buildbattlepro.settheme:
    description: Allow settheme command
    default: op
  buildbattlepro.bypass:
    description: Bypass commands while in arena
    default: op
  buildbattlepro.player:
    description: Player permissions
    default: true
    children:
      buildbattlepro.join: true
      buildbattlepro.leave: true
      buildbattlepro.changefloor: true
      buildbattlepro.changeweather: true
      buildbattlepro.changetime: true
      buildbattlepro.changebiome: true
      buildbattlepro.party: false
      buildbattlepro.joinfull: false
  buildbattlepro.changebiome:
    description: Change Biome permission
    default: true
  buildbattlepro.changefloor:
    description: Change Floor permission
    default: true
  buildbattlepro.changeweather:
    description: Change Weather permission
    default: true
  buildbattlepro.changetime:
    description: Change Time permission
    default: true
  buildbattlepro.manage.reports:
    description: Manage reports permission
    default: op





